# Generated by Django 5.2.7 on 2025-10-16 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('tst_id', models.IntegerField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(null=True)),
                ('number', models.IntegerField()),
                ('season', models.IntegerField()),
                ('tst_id', models.IntegerField(primary_key=True, serialize=False)),
                ('aired', models.BooleanField()),
                ('downloaded', models.BooleanField(default=False)),
                ('watched', models.BooleanField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.show')),
            ],
        ),
    ]
